## This is a set of functions that work together to save processing until the 
## actual calculation is needed.  In ddition to saving that, this allows to 
## values to be cached instead of reprocessing a potentially lengthy calculation 
## or function. 

###Test matricies
ma<-matrix(c(1,2,3,5,6,9,64,32,8),nrow=3,ncol=3)
ma4<-matrix(c(1,2,3,5,6,9,64,32,8,100,42,35,4,23,29,23),nrow=4,ncol=4)
id<-matrix(c(1,0,0,0,1,0,0,0,1),nrow=3,ncol=3)




## This function returns a list of 4 functions with an environment based on the 
## matrix that it was passed.  
## The 4 functions are set, get, setinverse, and getinverse
##    set -> sets the value of the vector
##    get -> gets the value of the vector
##    setinverse -> sets the value of the inverse matrix
##    getinverse-> gets the value of the inverse matrix

makeCacheMatrix <- function(x = matrix()) {
    i<-NULL
    set<- function(y) {
        x <<- y
        i <<- NULL 
    }
    get <- function() x
    setinverse <- function(solve) i <<- solve
    getinverse <- function() i
    list(set = set, get = get,
         setinverse = setinverse,
         getinverse = getinverse)
}


## this function takes the list of functions based on a particular matrix 
## generated by makeCacheMatrix.  With that if cacheSolve was called on that 
## particular list for the first time it actually calculates the inverse of the 
## matrix in that environment and chaches the result to save computation and 
## time in the future. If cacheSolve has been previously called on the lest; 
## then all it returns is the cached vales stored in the list.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    i <- x$getinverse()
    if(!is.null(i)) {
        message("getting cached data")
        return(i)
    }
    data <- x$get()
    i <- solve(data)
    x$setinverse(i)
    i
}
